version: '3.4'
services:
  workflow-test.avado.dappnode.eth:
    build: ./build
    image: 'workflow-test.avado.dappnode.eth:0.0.1'
    restart: always
    volumes:
      - 'data:/data'
    ports:
      - '12345:12345'
      - '12345:12345/UDP'
volumes:
  data: {}
